POST http://localhost:8080/users
Content-Type: application/json

{
  "login": "test@gmailcom",
  "name": "Azat"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "login": "test1@gmail.com",
  "name": "Daniil"
}

###

POST http://localhost:8080/events
Content-Type: application/json

{
  "login": "test@gmail.com",
  "name": "пара в JavaLab",
  "eventStarts": "2030-12-25T19:00:13",
  "eventEnds": "2030-12-25T20:30:00"
}

###
POST http://localhost:8080/events
Content-Type: application/json

{
  "login": "test@gmail.com",
  "eventStarts": "2016-12-25T19:00:13",
  "eventEnds": "2016-12-25T20:30:00"
}

###
POST http://localhost:8080/events/several
Content-Type: application/json

{
  "logins": [
    "tesgmail.com",
    "test@gmail.com"
  ],
  "name": "Созвон по проекту",
  "eventStarts": "2019-12-25T19:00:13",
  "eventEnds": "2019-12-25T20:30:00"
}

###

POST http://localhost:8080/events/time/free
Content-Type: application/json

{
  "logins": [
    "test1@gmail.com",
    "test@gmail.com"
  ]
}